# 1. Imports

In [ ]:
%load_ext autoreload
%autoreload 2

import os
import glob
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 500)
pd.options.plotting.backend = "plotly"

# 2. Data

### 2.1 Données de validation de titres.

In [10]:

# 4 fichiers csv de validations de titres par trimestre pour 2025 à combiner

# Chemin du répertoire où se trouvent les fichiers csv à combiner
folder_path_validations = os.path.join("..","data","validations_multiples")

# Récuperer tous les fichiers csv dans ce répertoire
validations = glob.glob(os.path.join(folder_path_validations, "*.csv"))

# List comprehension pour lire et concaténer
validations_df = pd.concat((pd.read_csv(f, sep=";") for f in validations), ignore_index=True)

# Sauvegarder le résultat dans un nouveau csv 
#validations_df.to_csv("../data/validations/validations.csv", index=False)

print(f"Successfully stacked {len(validations)} CSV files into 'validations.csv'!")

Successfully stacked 4 CSV files into 'validations.csv'!

### 2.2 Liste et emplacement des gares / stations.

#### 2.2.1. Liste des stations généralisée.

In [16]:
#Liste des stations généralisée (une station peut regrouper plusieurs lignes de transport associées)
filepath_stations_g = os.path.join("..","data","stations","emplacement-des-gares-idf-data-generalisee.csv")
stations_g_df = pd.read_csv(filepath_stations_g, sep=";")

#### 2.2.2. Liste des stations.

In [17]:
#Liste des stations (une station par ligne de transport associée)
filepath_stations = os.path.join("..","data","stations","emplacement-des-gares-idf.csv")
stations_df = pd.read_csv(filepath_stations,sep=";")

# 3. EDA

### 3.1. Données de validation de titres.

In [4]:
validations_df.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
0,2025-10-31,800.0,803,454,69662.0,SAULES,Autres titres,1.0
1,2025-10-31,800.0,803,454,69662.0,SAULES,Forfaits courts,188.0
2,2025-10-31,800.0,803,788,60987.0,SAVIGNY SUR ORG,Imagine R,1263.0
3,2025-10-31,800.0,803,793,59842.0,SERMAISE,Amethyste,1.0
4,2025-10-31,800.0,803,793,59842.0,SERMAISE,Forfait Navigo,42.0

In [5]:
validations_df.shape

(1892453, 8)

In [6]:
validations_df.columns

Index(['jour', 'code_stif_trns', 'code_stif_res', 'code_stif_arret', 'id_zdc',
       'libelle_arret', 'categorie_titre', 'nb_vald'],
      dtype='object')

In [7]:
validations_df.describe()

       code_stif_trns        id_zdc       nb_vald
count    1.892453e+06  1.890831e+06  1.892453e+06
mean     5.020467e+02  9.026463e+04  1.140139e+03
std      3.472100e+02  8.951037e+04  3.084966e+03
min      1.000000e+02 -1.000000e+00  1.000000e+00
25%      1.000000e+02  6.653500e+04  4.400000e+01
50%      8.000000e+02  7.115000e+04  2.150000e+02
75%      8.000000e+02  7.192000e+04  1.016000e+03
max      8.100000e+02  9.999990e+05  9.997000e+04

In [8]:
validations_df.describe(include=object)

              jour code_stif_res code_stif_arret libelle_arret categorie_titre
count      1892453       1892453         1892453       1892453         1892453
unique         365            18             787           779               8
top     2025-11-04           110           48093  GARE DE LYON  Forfait Navigo
freq          5365        806414            8905          7665          284117

### 3.2. Liste et emplacement des gares / stations.

#### 3.2.1. Liste des stations généralisée.

In [32]:
stations_g_df.head()

,geo_point_2d,geo_shape,objectid_1,codeunique,nom_long,nom_so_gar,nom_su_gar,id_ref_zdc,nom_zdc,id_ref_zda,nom_zda,idrefliga,idrefligc,res_com,mode,train,rer,metro,tramway,val,tertrain,terrer,termetro,tertram,terval,exploitant,idf,principal,x,y
0,"48.88218913760796, 2.70601418111842","{""coordinates"": [2.70601418111842, 48.88218913...",5,3,Lagny-Thorigny,NaN,NaN,68494,Lagny - Thorigny,427872,Lagny - Thorigny,A01844,C01730,TRAIN P,TRAIN,1,0,0,0,0,0,0,0,0,0,SNCF,1,0,678439.8038,6.864726e+06
1,"48.83964551726303, 2.655130086641314","{""coordinates"": [2.655130086641314, 48.8396455...",7,7,Torcy,NaN,NaN,68129,Torcy,43207,Torcy,A01856,C01742,RER A,RER,0,1,0,0,0,0,0,0,0,0,RATP,1,0,674687.4504,6.860010e+06
2,"48.79565482051668, 2.6503876698084805","{""coordinates"": [2.650387669808481, 48.7956548...",9,10,Roissy-en-Brie,NaN,NaN,67839,Roissy-en-Brie,46568,Roissy-en-Brie,A01843,C01729,RER E,RER,1,1,0,0,0,0,0,0,0,0,SNCF,1,0,674317.7148,6.855121e+06
3,"48.77077891616031, 2.690252782201096","{""coordinates"": [2.690252782201096, 48.7707789...",10,11,Ozoir-la-Ferrière,NaN,NaN,462934,Ozoir-la-Ferrière,462901,Ozoir-la-Ferrière,A01843,C01729,RER E,RER,1,1,0,0,0,0,0,0,0,0,SNCF,1,0,677235.3132,6.852342e+06
4,"48.960226490735955, 2.9500603827528087","{""coordinates"": [2.950060382752809, 48.9602264...",13,16,Trilport,NaN,NaN,68984,Trilport,47962,Trilport,A01844,C01730,TRAIN P,TRAIN,1,0,0,0,0,0,0,0,0,0,SNCF,1,0,696343.0315,6.873365e+06

In [33]:
stations_g_df.shape

(999, 30)

In [34]:
stations_g_df.columns

Index(['geo_point_2d', 'geo_shape', 'objectid_1', 'codeunique', 'nom_long',
       'nom_so_gar', 'nom_su_gar', 'id_ref_zdc', 'nom_zdc', 'id_ref_zda',
       'nom_zda', 'idrefliga', 'idrefligc', 'res_com', 'mode', 'train', 'rer',
       'metro', 'tramway', 'val', 'tertrain', 'terrer', 'termetro', 'tertram',
       'terval', 'exploitant', 'idf', 'principal', 'x', 'y'],
      dtype='object')

#### 3.2.2. Liste des stations.

In [29]:
stations_df.head()

,geo_point_2d,geo_shape,objectid_1,id_gares,nom_gares,nom_so_gar,nom_su_gar,id_ref_zdc,nom_zdc,id_ref_zda,nom_zda,idrefliga,idrefligc,res_com,indice_lig,mode,tertrain,terrer,termetro,tertram,terval,exploitant,idf,principal,x,y,picto,nom_iv
0,"48.667901961049886, 2.5475480458143664","{""coordinates"": [2.547548045814366, 48.6679019...",91,196,Combs-la-Ville - Quincy,NaN,NaN,62558,Combs-la-Ville - Quincy,45771,Combs-la-Ville - Quincy,A01842,C01728,RER D,D,RER,0,0,0,0,0,SNCF,1,0,666681.8714,6.840955e+06,https://data.iledefrance-mobilites.fr/api/expl...,Combs-la-Ville - Quincy
1,"48.613427913594734, 2.4729336504587436","{""coordinates"": [2.472933650458744, 48.6134279...",94,207,Corbeil-Essonnes,NaN,NaN,60309,Corbeil-Essonnes,43115,Corbeil-Essonnes,A01842,C01728,RER D,D,RER,0,0,0,0,0,SNCF,1,1,661146.9910,6.834933e+06,https://data.iledefrance-mobilites.fr/api/expl...,Corbeil-Essonnes
2,"48.843772576851464, 2.3739164698064985","{""coordinates"": [2.373916469806499, 48.8437725...",128,307,Gare de Lyon,NaN,NaN,73626,Gare de Lyon,470195,Gare de Lyon,A01842,C01728,RER D,D,RER,0,0,0,0,0,SNCF,1,1,654051.0804,6.860596e+06,https://data.iledefrance-mobilites.fr/api/expl...,Gare de Lyon
3,"49.03318276903128, 2.478033365115082","{""coordinates"": [2.478033365115082, 49.0331827...",190,452,Les Noues,NaN,NaN,66650,Les Noues,47968,Les Noues,A01842,C01728,RER D,D,RER,0,0,0,0,0,SNCF,1,0,661831.4373,6.881603e+06,https://data.iledefrance-mobilites.fr/api/expl...,Les Noues
4,"49.13828637527201, 2.4901789854211955","{""coordinates"": [2.490178985421196, 49.1382863...",242,957,Orry-la-Ville-Coye-la-Forêt,NaN,NaN,411422,Orry-la-Ville - Coye,411421,Orry-la-Ville - Coye,A01842,C01728,RER D,D,RER,0,0,0,0,0,SNCF,0,1,662795.0403,6.893287e+06,https://data.iledefrance-mobilites.fr/api/expl...,Orry-la-Ville-Coye-la-Forêt

In [30]:
stations_df.shape

(1240, 28)

In [31]:
stations_df.columns

Index(['geo_point_2d', 'geo_shape', 'objectid_1', 'id_gares', 'nom_gares',
       'nom_so_gar', 'nom_su_gar', 'id_ref_zdc', 'nom_zdc', 'id_ref_zda',
       'nom_zda', 'idrefliga', 'idrefligc', 'res_com', 'indice_lig', 'mode',
       'tertrain', 'terrer', 'termetro', 'tertram', 'terval', 'exploitant',
       'idf', 'principal', 'x', 'y', 'picto', 'nom_iv'],
      dtype='object')